### ISSUE TITLE
No exterior sound in new FG versions

### ISSUE THREAD

**Issue by CA1012** [FGMEMBERS/787-8#4]
@FL2070 I think that the sounds on the 787-8 and -9 are broken. they do not work on the outside views (Helicopter and Chase and I'm not sure about the others) but it dose work on the interior views and around the aircraft. Can you take a look?

**Comment by YV3399** [comment]
Hello @CA1012 seen the error and solved by my, and it is already uploaded on github

**Comment by CA1012** [comment]
Thanks @GabrielVenezuela. Can you see if the 787-9 has the same problem or are the sounds dependent on the 787-8?

**Comment by YV3399** [comment]
ok I check

**Comment by YV3399** [comment]
ready problem solved in 787-9

**Comment by CA1012** [comment]
Thanks.
